dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
    - secure: "rgPXKViXZpp/iVU9FQ2Bu0KZ65kuaW3VrwaH0qIllYTW0W1oOgzC7u8B9pqz9zGiuGAQL7i930rZGEe7p5cSI2NsZAz1hxgmT/J6CaqBVEpWhTBqpcv6OkiAMtHK5May6/ft5xMyZsQB7mU78aS+a+BW4aR14y7f+gYFOetyy+sMNPahQxZcMkxoyYoBI3Pai5iiFE4YL6A5sLDr27qy5vJnhViQAP4JopdSbtFTyjLT0T5/GmfWsH2QcggIVnD/9yntnv/E4O5wOlEnpxa7mE+Q1NZc/hVjbyNdaM/ZwRYcTBnDpjPq0rz/GelHHbgYrVXdsAyMFuuNnk9uQOl8iDf/d6HRHXwtk6kV+93V1hZsBiQh8YX86c+rzQToYQ6b3R+1OE9cwjaUJhCXNyX4/Rd2VlixC+laL720zsPr+af9Bw0Ww3Aya9rXNQkX17/BC/ndLcXCdKp3Bhg98hOHQoVR6h4d2rAWQEeXCDSrooDJgyGq/QqnTcCfNEh8+sKvUaauXrZPlANaOCexUFI2XOy/ognvTY1uDj9twVCBmWpqQsgAy4vtg/P15UVeNSgfhA8hFurAjva6KZxB+/Ol6rNlFQby/K8vbH6I0yx2SBnZE2mQUfkwK8EDzMmuGrRUbj6jgCu8CqEFvPxsnEpbssGfpYgyiOoU6VbtEOvSaFo="
    - secure: "ds1T9cRUqt1NHK1n5uoiRudguPtbfNGvfiFGlrQJmEcb0ne7Ykfk9pY9d6b+rFIVUu8nfCOqjXyS8gzn8izjzXwjdYOZosuKPvwPJcJiy0DtEW8oDy82/JlqoGQf0aWwb7KNXcqM0SSm863hS3uxochMdNZjnWv6Kl4dRAM/iz3TOCADRUoA2k7Izq4jZHA7Z0NPasTbqkT3gYwv6g2/FarNOLBDU4sJxcWdzvcNu8763jtQVOLDOny1iZ1xDhq6y3RohVHdwr6juetott6i08GAxMyWbjEVVtd1xuyO0+yaWgMBkrST/SEIqQ95W+muxc8TAo6c6u+BEjAx4jUgcUBr1B+AQesFs/5ghkgJFevAeqqfVkb+12pBR4Cf7fJqElDxHkbb15NB4adeXitwHG/Q+lM4m0LuDjgwmOVzSYwZDohNzRZ2NMcICuf7ttgu6MKEXNOyQkDGR7vLGjYxkZzYPUwSnO+6fINlgDVLXCsEXtnktPQC4ewonThJ8t73c2fJVIZbhxD42B7hzacdayAbzgDj/LuXxsLRPgWKGsB/joG9nsyq8RyoXH4pc/ilEcpV7hGTr+BacomBbUymLVk0GQYelT0ekM5KLL8jxOtGNfyWqLTIwYNqUPUAr0fJAA2i7dAVGSuoAdPd6NLrlb1NJHJyfzjYeNVogcS5wJA="
    - secure: "TtzX26JHJ8AxaroL32kkImHHCZ6MOqmpOWGMTdhBv/BaWdtWKUvydzfXnH0mW87jfgAU9+35+CJCt9eI4EXIWJWKqQHk1tT0LYoPjW/53XSUbr2/zIq+xa7ZkuEXgSqX6Gg5HQGl8VATRGrt+v0cjfAe50NMj+v/br9ZoK6irq+SAy9VNdG5Gu/tOC/uB/Po1Vkj9LbhkJEv4baaJIrDXSPgQt0yX2Ky7RBx6/qvDm7D5GEj6PHHvX81FPaW5xDzzSQRQ79WNkdpfy5XXnwrUFOcnd5bKYQpdGxdKwYYsHr4NMB02lj3+RKOea/g6S0UGN8yoFEd/lAW9l3F9nRlvs8g8C34oK5MWdOvMxTQYIsDGZMhEOPMhuYJMdaLA8L+3nVgwimm3whJNpwOa1PAeFvNhiW7XwzPtFt5Ks6b81tAvTf3wgSs3FSq+ZxRgQN+whlplySbXheK6179q2OB27Y7+Ph0m1eHtFw++u9VAyMAS65A2GZbYxSnVQQwrcXUUhQqzkUyfjvvlQz9zqBPLO3MRI1mp3WVgcy9pHJ104qz5XVcM253CK3svZifcySjJcJhDlrCd7EONKszttBooMWC6sp1PpgkBFPv/Q/JvQroYmyDxGkEYKYx4r/FWWXgkW8Ghz2hWcFdM1v3Euca58nwKCt4ez0e9sD8yC6oUX4="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/my-docker-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: user-api-test-v2